WebProject/urls.py
from django.contrib import admin
from django.urls import path, include
from WebProject.views import home_page
from accounts import views as acc_views
from .views import home_page
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', home_page, name='home'),
    path('',include('class.urls')),

]

urlpatterns += staticfiles_urlpatterns()

class/urls.py
from django.urls import path, include, re_path
from .views import AddClass, class_registration, class_list, team_registration, ClassesView, TeamView, member_list, \
    MemberView, student_list,create_quiz,QuizView,add_question,quiz_list,question_list

app_name = 'class'

urlpatterns = [
    path('addclass/', class_registration, name='create_class'),
    path('classlist/', ClassesView.as_view(), name='class_list'),

    path('classlist/<slug>/studentlist', student_list, name='student_list'),
    path('teamlist/', TeamView.as_view(), name='team_list'),
    path('teamlist/<slug>/memberlist', MemberView.as_view(), name='member_list'),
    path('createquiz/', create_quiz, name='create_quiz'),
    path('createquiz/<slug>/addquestions/<int:p>', add_question, name='add_question'),
    path('quizlist/', quiz_list, name='quiz_list'),
path('quizlist/<slug>/questionlist', question_list, name='question_list'),
    # path(r'^(?P<slug>[\w-]+)/memberslist', member_list, name='member_list'),

    # path(r'^(?P<slug>[\w-]+)/$', ClassesView.as_view(), name='class_view'),
    path('addteam/', team_registration, name='create_team'),

    # path('addquiz',)
]

templates/base/asidebar.html
{% load static %}
<aside class="aside-menu">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab"><i class="icon-list"></i></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#settings" role="tab"><i class="icon-settings"></i></a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="timeline" role="tabpanel">
            <div class="callout m-0 py-2 text-muted text-center bg-light text-uppercase">
                <small><b>Today</b></small>
            </div>
            <hr class="transparent mx-3 my-0">
            <div class="callout callout-warning m-0 py-3">
                <div class="avatar float-right">
                    <img src="{% static 'src/img/avatars/7.jpg' %}" class="img-avatar" alt="admin@bootstrapmaster.com">
                </div>
                <div>Meeting with
                    <strong>Lucas</strong>
                </div>
                <small class="text-muted mr-3"><i class="icon-calendar"></i>&nbsp; 1 - 3pm</small>
                <small class="text-muted"><i class="icon-location-pin"></i>&nbsp; Palo Alto, CA</small>
            </div>
            <hr class="mx-3 my-0">
            <div class="callout callout-info m-0 py-3">
                <div class="avatar float-right">
                    <img src="{% static 'src/img/avatars/4.jpg' %}" class="img-avatar" alt="admin@bootstrapmaster.com">
                </div>
                <div>Skype with
                    <strong>Megan</strong>
                </div>
                <small class="text-muted mr-3"><i class="icon-calendar"></i>&nbsp; 4 - 5pm</small>
                <small class="text-muted"><i class="icon-social-skype"></i>&nbsp; On-line</small>
            </div>
        </div>
        <div class="tab-pane p-3" id="settings" role="tabpanel">
            <h6>Settings</h6>
            <hr>
            <h6>System Utilization</h6>

            <div class="text-uppercase mb-1 mt-4">
                <small><b>CPU Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-info" role="progressbar" style="width: 25%" aria-valuenow="25"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">348 Processes. 1/4 Cores.</small>

            <div class="text-uppercase mb-1 mt-2">
                <small><b>Memory Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-warning" role="progressbar" style="width: 70%" aria-valuenow="70"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">11444GB/16384MB</small>

            <div class="text-uppercase mb-1 mt-2">
                <small><b>SSD 1 Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">243GB/256GB</small>

            <div class="text-uppercase mb-1 mt-2">
                <small><b>SSD 2 Usage</b></small>
            </div>
            <div class="progress progress-xs">
                <div class="progress-bar bg-success" role="progressbar" style="width: 10%" aria-valuenow="10"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <small class="text-muted">25GB/256GB</small>
        </div>
    </div>
</aside>

templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<!--Headers-->
{% include 'base/header.html' %}

<!-- BODY options, add following classes to body to change options

// Header options
1. '.header-fixed'					- Fixed Header

// Brand options
1. '.brand-minimized'       - Minimized brand (Only symbol)

// Sidebar options
1. '.sidebar-fixed'					- Fixed Sidebar
2. '.sidebar-hidden'				- Hidden Sidebar
3. '.sidebar-off-canvas'		- Off Canvas Sidebar
4. '.sidebar-minimized'			- Minimized Sidebar (Only icons)
5. '.sidebar-compact'			  - Compact Sidebar

// Aside options
1. '.aside-menu-fixed'			- Fixed Aside Menu
2. '.aside-menu-hidden'			- Hidden Aside Menu
3. '.aside-menu-off-canvas'	- Off Canvas Aside Menu

// Breadcrumb options
1. '.breadcrumb-fixed'			- Fixed Breadcrumb

// Footer options
1. '.footer-fixed'					- Fixed footer

-->

<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden" style="font-size:0.875rem">
<!--Navbar-->
{% include 'base/navbar.html' %}

<div class="app-body">
    <!--Sidebar-->
    {% include 'base/sidebar.html' %}

    <!-- Main content -->
    <main class="main">

        <!-- Breadcrumb -->
        {% include 'base/breadcrumb.html' %}

        <!-- Page contents -->
        <div class="container-fluid">
            <div class="animated fadeIn">
                {% block content %}
                {% endblock %}
            </div>

        </div>
        <!-- /.conainer-fluid -->
    </main>


    <!--Aside bar-->
    {% include 'base/asidebar.html' %}

</div>

<!--Footer-->
{% include 'base/footer.html' %}

<!--JS-->
{% include 'base/js.html' %}

</body>
</html>

templates/base/breadcrumb.html
{% load static %}
<ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item"><a href="#">Admin</a></li>
    <li class="breadcrumb-item active">Dashboard</li>

    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
        <div class="btn-group" role="group" aria-label="Button group">
            <a class="btn" href="#"><i class="icon-speech"></i></a>
            <a class="btn" href="{% url 'home' %}"><i class="icon-graph"></i> &nbsp;Dashboard</a>
            <a class="btn" href="#"><i class="icon-settings"></i> &nbsp;Settings</a>
        </div>
    </li>

    {% block breadcrumb %}
    {% endblock %}
</ol>

templates/base/footer.html
<footer class="app-footer">
    <span><a href="#">Jangal Badhal High School</a> © 2020</span>
    <span class="ml-auto">Powered by <a href="https://www.twitter.com/sajib1066">Sajib Hossain</a></span>
    {% block extrafooter %}
    {% endblock %}
</footer>

templates/base/header.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Neging ">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="{% static 'src/img/favicon.png' %}">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

<style>
   *{
       font-size: 16px;!important;
   }
   div.container-fluid{
        padding-right: 0;
   }
   div.card{
       border-color: #00a67c;
        border-width: 9px;
       border-radius: 12px;
       padding: 0 0px;
   }
header.app-header.navbar{
    background-color: #33444c;
}
   input.btn-primary {
       background-color: #33444c;
   }
    .main .container-fluid {!important;

}
    .main{background-color: white}
    .container-fluid {!important;
    width: 100%;
    padding-right: 0px;
    padding-left: 0px;
    margin-right: auto;
    margin-left: auto;
}
</style>
    <!-- Icons -->
    <link href="{% static 'dist/vendors/css/simple-line-icons.min.css' %}" rel="stylesheet">

    <link href="{% static 'dist/vendors/css/font-awesome.min.css' %}" rel="stylesheet">

    <!-- Main styles for this application -->
    <link href="{% static 'dist/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'src/css/form.css' %}" rel="stylesheet">

    {% block extrahead %}
    {% endblock %}
</head>

templates/base/js.html
{% load static %}

<!-- Bootstrap and necessary plugins -->
<script src="{% static 'dist/vendors/js/popper.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/pace.min.js' %}"></script>

<!-- Plugins and scripts required by all views -->
<!--Chart JS is commented out due to console errors-->
<!--<script src="{% static 'dist/vendors/js/Chart.min.js' %}"></script>-->

<!-- CoreUI main scripts -->

<script src="{% static 'dist/js/app.js' %}"></script>

<!-- Plugins and scripts required by this views -->

<!-- Custom scripts required by this view -->
<script src="{% static 'dist/js/views/main.js' %}"></script>
<script src="{% static 'src/js/attendance.js' %}"></script>

{% block script %}

{% endblock %}

templates/base/navbar.html
{% load static %}
<header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav d-md-down-none">

    </ul>
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="true" aria-expanded="false">
                {% if request.user.userprofile %}
                <img src="{{ request.user.userprofile.photo.url }}" class="img-avatar" alt="admin">
                {% else %}
                <img src="{% static 'src/img/man.png' %}" class="img-avatar" alt="Anynumos">
                {% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>Account</strong>
                </div>
                <a class="dropdown-item" href="#"><i class="fa fa-bell-o"></i> Updates<span
                        class="badge badge-info">42</span></a>
                <div class="dropdown-header text-center">
                    <strong>Settings</strong>
                </div>
                <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Profile</a>
                <a class="dropdown-item" href="#"><i class="fa fa-wrench"></i> Settings</a>
                <a class="dropdown-item" href="#"><i class="fa fa-usd"></i> Payments<span class="badge badge-secondary">42</span></a>
                <a class="dropdown-item" href="#"><i class="fa fa-lock"></i> Logout</a>
            </div>
        </li>
    </ul>
    <button class="navbar-toggler aside-menu-toggler" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    {% block navbar %}
    {% endblock %}

</header>

templates/base/sidebar.html
{% load static %}
<div class="sidebar" style="background-color: #00a67c">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="icon-speedometer"></i> Dashboard</a>
            </li>
            <!-- Administration Section Start -->
            <li class="nav-item nav-dropdown">
                <!-- Administration Section END -->

                <!-- Academic Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>My Team</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'class:create_team' %}">
                            <i class="fa fa-plus-circle"></i>Add Team</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'class:team_list' %}">
                            <i class="fa fa-list"></i>Team List</a>


                    </li>

                </ul>
            </li>
            <!-- Academic Section END -->

            <!-- Teacher Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Teacher</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-plus-circle"></i>Teacher Registration</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-list"></i>Teacher List</a>
                    </li>
                </ul>
            </li>
            <!-- Teacher Section END -->

            <!-- Class Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Class</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'class:create_class' %}">
                            <i class="fa fa-plus-circle"></i>Class Registration</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'class:class_list' %}">
                            <i class="fa fa-list"></i>Class List</a>
                    </li>
                </ul>
            </li>
            <!-- Quiz Section END -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Quiz</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'class:create_quiz' %}">
                            <i class="fa fa-plus-circle"></i>Create Quiz</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'class:quiz_list' %}">
                            <i class="fa fa-list"></i>Quiz List</a>
                    </li>
                </ul>
            </li>



            <!-- Student Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Student</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-plus-circle"></i>Student Registration</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-list"></i>Student List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-search-plus"></i>Student Search</a>
                    </li>
                </ul>
            </li>
            <!-- Student Section END -->

            <!-- Enroll Student Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Enroll Student</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-plus-circle"></i>Student Enrolled</a>
                        <a class="nav-link" href="#">
                            <i class="fa fa-list"></i>Enrolled Student List</a>
                    </li>
                </ul>
            </li>
            <!-- Enroll Student Section END -->

            <!-- Employee Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Employee</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-plus-circle"></i>Add Employee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-list"></i>Employee List</a>
                    </li>
                </ul>
            </li>
            <!-- Employee Section END -->

            <!-- Result Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Result</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-plus-circle"></i>Add Subject</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-list"></i>Subject List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-plus-circle"></i>Mark Entry</a>
                    </li>
                </ul>
            </li>
            <!-- Result Section END -->

            <!-- Attendence Report Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Attendence Report</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-plus-circle"></i>Student Attendence</a>
                    </li>
                </ul>
            </li>
            <!-- Attendence Report Section END -->

            <!-- Holiday Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Holiday</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="nav-icon icon-puzzle"></i>Student List</a>
                    </li>
                </ul>
            </li>
            <!-- Holiday Section END -->

            <!-- Event Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="nav-icon icon-puzzle"></i>Event</a>
                <ul class="nav-dropdown-items">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="nav-icon icon-puzzle"></i>Student List</a>
                    </li>
                </ul>
            </li>
            <!-- Event Section END -->

            <!-- User-Manual Section START -->
            <li class="nav-item nav-dropdown">
                <a class="nav-link" href="#">
                    <i class="nav-icon icon-puzzle"></i>User-Manual</a>
            </li>
            <!-- User-Manual Section END -->
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>

    {% block sidebar %}
    {% endblock %}
</div>